version: '3.3'
networks:
  laravel: 
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports: 
      - 8080:80
    links: 
      - fpm  
    volumes:
      - ./:/var/www/laravel-docker  
  fpm: 
    build: 
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel-docker
    links:
      - mysql
  mysql: 
    image: mysql:5.7
    ports: 
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=laravel
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080